import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { EventEmitter } from 'node:events';
import { readFile, readdir } from 'node:fs/promises';
import { PassThrough } from 'node:stream';
import { ensureOpencodeServer, resetOpencodeServerSingletonForTests, createOpencodeHttpClient } from '../host/opencode-client.mjs';
import { createOpenCodeBoundary, publicOpenCodeError } from '../host/opencode-boundary.mjs';
const turn=()=>new Promise(r=>setImmediate(r));
const errorCode=async fn=>{try{await fn();return null;}catch(e){return e.code;}};
const ops=['start','prompt','permission','messages','abort','diff','rename','delete','archive','list','agents','stop'];
const scoped=['prompt','permission','messages','abort','diff','rename','delete','archive'];
function fixture(t, overrides={}) {
  const password=randomBytes(32).toString('base64url'), header='Basic '+Buffer.from('opencode:'+password).toString('base64');
  let calls=0,input,enabled=true,live=1;
  const child=new EventEmitter(); child.kill=()=>{live=0;child.exitCode=0;child.emit('exit');};
  const info={baseUrl:'http://127.0.0.1:45125',directory:'/fixture',auth:{username:'opencode',password,header},process:child};
  const logs=[], outputs=[];
  const client={createSession:async()=>({id:'A'}),listSessions:async()=>[{id:'A',title:'title'}],supportsPromptMessageId:async()=>false,prompt:async()=>null,replyPermission:async()=>true,messages:async()=>[],abort:async()=>true,sessionDiff:async()=>[],rename:async()=>({id:'A'}),remove:async()=>true,archive:async()=>({id:'A'}),listAgents:async()=>[{name:'build'}]};
  const counted=new Proxy(client,{get(target,key){return typeof target[key]==='function'? (...args)=>{calls++;return target[key](...args);}:target[key];}});
  const options={ensureServer:async()=>{calls++;if(info.process.exitCode!=null){const fresh=new EventEmitter();fresh.kill=()=>{live=0;fresh.exitCode=0;fresh.emit('exit');};info.process=fresh;live=1;}return info;},createClient:()=>counted,fetchImpl:async()=>{calls++;return new Response(new ReadableStream({start(c){input=c;}}),{headers:{'content-type':'text/event-stream'}});},executionEnabled:async()=>enabled,forgetServer:async()=>{},log:(...a)=>logs.push(a),...overrides};
  const boundary=createOpenCodeBoundary(options);t.after(()=>boundary.dispose());
  return {boundary,client,info,logs,outputs,get calls(){return calls;},reset(){calls=0;},set enabled(v){enabled=v;},get live(){return live;},async send(e){const bytes=Buffer.from(`data: ${JSON.stringify(e)}\n\n`);for(let i=0;i<bytes.length;i+=7)input.enqueue(bytes.subarray(i,i+7));await turn();}};
}
const payload=(sessionId='A')=>({sessionId,text:'hello',permissionId:'p',decision:{approved:true},title:'title'});
const bodyFor=(op,id='A')=> op==='prompt'?{sessionId:id,text:'hello'}:op==='permission'?{sessionId:id,permissionId:'p',decision:{approved:true}}:op==='rename'?{sessionId:id,title:'title'}:scoped.includes(op)?{sessionId:id}:{};
test('start returns only session id',async t=>{const f=fixture(t);assert.deepEqual(await f.boundary.run('start',{}),{ok:true,sessionId:'A'});});
test('list exposes no upstream connection fields',async t=>{const f=fixture(t);f.client.listSessions=async()=>[{id:'A',auth:f.info.auth,baseUrl:f.info.baseUrl,eventUrl:'x',eventAuthorization:f.info.auth.header}];const value=await f.boundary.run('list',{});const count=v=>v&&typeof v==='object'?Object.entries(v).reduce((n,[k,x])=>n+(/auth|password|baseUrl|eventUrl/i.test(k)?1:0)+count(x),0):0;assert.equal(count(value),0);});
for(const op of ops)test(`disabled route does no upstream work: ${op}`,async t=>{const f=fixture(t);f.enabled=false;await errorCode(()=>f.boundary.run(op,bodyFor(op)));assert.equal(f.calls,0);});
for(const op of ops.filter(v=>!['start','list','stop'].includes(v)))test(`missing server does not respawn: ${op}`,async t=>{const f=fixture(t);assert.equal(await errorCode(()=>f.boundary.run(op,bodyFor(op))),'OPENCODE_UNAVAILABLE');});
for(const op of scoped)test(`unknown session is refused: ${op}`,async t=>{const f=fixture(t);await f.boundary.run('start',{});assert.equal(await errorCode(()=>f.boundary.run(op,bodyFor(op,'unknown'))),'OPENCODE_SESSION_UNKNOWN');});
test('unknown permission cannot cross sessions',async t=>{const f=fixture(t);f.client.listSessions=async()=>[{id:'A'},{id:'B'}];await f.boundary.run('list',{});await f.send({type:'permission.asked',properties:{sessionID:'B',id:'p'}});let calls=0;f.client.replyPermission=async()=>{calls++;};await errorCode(()=>f.boundary.run('permission',bodyFor('permission')));assert.equal(calls,0);});
test('history with foreign part is refused',async t=>{const f=fixture(t);await f.boundary.run('start',{});f.client.messages=async()=>[{info:{id:'m',role:'assistant',sessionID:'A'},parts:[{id:'p',messageID:'m',sessionID:'B',type:'text',text:'foreign'}]}];assert.equal(await errorCode(()=>f.boundary.run('messages',{sessionId:'A'})),'OPENCODE_PROTOCOL_ERROR');});
for(const [kind,expected] of [[401,'OPENCODE_UPSTREAM_AUTH'],[403,'OPENCODE_UPSTREAM_AUTH'],[500,'OPENCODE_UPSTREAM_FAILED'],[503,'OPENCODE_UPSTREAM_FAILED'],['network','OPENCODE_UPSTREAM_FAILED'],['timeout','OPENCODE_TIMEOUT']])test(`upstream failure is typed: ${kind}`,async t=>{
  const f=fixture(t,{createClient:(baseUrl,opts)=>createOpencodeHttpClient({baseUrl,...opts,requestTimeoutMs:10,fetchImpl:async url=>{
    if(new URL(url).pathname==='/session')return new Response('{"id":"A"}');
    if(typeof kind==='number')return new Response('upstream private body',{status:kind});
    if(kind==='network')throw Object.assign(new Error('fixture'),{code:'ECONNRESET'});
    return new Promise(()=>{});
  }})});
  await f.boundary.run('start',{});const code=await errorCode(()=>f.boundary.run('messages',{sessionId:'A'}));
  let streamCode=code;
  if(typeof kind==='number'){const s=fixture(t,{fetchImpl:async()=>new Response('upstream private body',{status:kind})});streamCode=await errorCode(()=>s.boundary.run('start',{}));}
  assert.equal(code===streamCode?code:'inconsistent failure mapping',expected);
});
test('unexpected exception has fixed typed body',async t=>{const f=fixture(t);await f.boundary.run('start',{});f.client.messages=async()=>{throw new Error(randomBytes(32).toString('hex'));};const code=await errorCode(()=>f.boundary.run('messages',{sessionId:'A'}));const result=publicOpenCodeError(code);assert.deepEqual([result.status,result.payload.code],[500,'OPENCODE_INTERNAL']);});
test('subscription quota cannot open another reader',async t=>{const f=fixture(t);await f.boundary.run('start',{});for(let i=0;i<8;i++)await f.boundary.openEvents('A');assert.equal(await errorCode(()=>f.boundary.openEvents('A')),'OPENCODE_LIMIT');});
test('upstream malformed JSON never passes through',async t=>{const f=fixture(t);await f.boundary.run('start',{});f.client.messages=async()=>'{';assert.equal(await errorCode(()=>f.boundary.run('messages',{sessionId:'A'})),'OPENCODE_PROTOCOL_ERROR');});
test('stop deletes generation and registry',async t=>{const f=fixture(t);await f.boundary.run('start',{});await f.boundary.run('stop',{});assert.equal(await errorCode(()=>f.boundary.openEvents('A'))!==null,true);});
test('late start after revocation cannot resurrect server',async t=>{let resolve,entered;const started=new Promise(r=>{entered=r;});let info;const f=fixture(t,{ensureServer:async()=>{entered();return new Promise(r=>{resolve=r;});}});info=f.info;const pending=errorCode(()=>f.boundary.run('start',{}));await started;await f.boundary.revoke();resolve(info);await pending;await turn();assert.equal(f.live,0);});
test('revocation suppresses already-resolved queued event',async t=>{const f=fixture(t);await f.boundary.run('start',{});const sub=await f.boundary.openEvents('A'),iterator=sub.events[Symbol.asyncIterator]();await iterator.next();await f.send({type:'session.updated',properties:{info:{id:'A',title:'late'}}});const pending=iterator.next();const revoke=f.boundary.revoke();const result=await pending;await revoke;assert.equal(result.done?0:1,0);});
test('secrets never reach extension bodies headers or raw logs',async t=>{const f=fixture(t);const forbidden=[f.info.auth.password,f.info.auth.header,f.info.auth.header.slice(6),f.info.baseUrl];forbidden.push(...forbidden.map(v=>encodeURIComponent(v)));const secret=forbidden.join(' ');const outputs=[];f.client.createSession=async()=>({id:'A',auth:f.info.auth});outputs.push(await f.boundary.run('start',{}));const sub=await f.boundary.openEvents('A');await sub.events[Symbol.asyncIterator]().next();await f.send({type:'session.updated',properties:{info:{id:'A',title:secret},authorization:f.info.auth.header}});outputs.push((await sub.events[Symbol.asyncIterator]().next()).value);f.client.listSessions=async()=>[{id:'A',title:secret,auth:f.info.auth}];f.client.messages=async()=>[{info:{sessionID:'A',id:'m',role:'user'},parts:[{sessionID:'A',messageID:'m',id:'p',type:'text',text:secret}]}];f.client.sessionDiff=async()=>[{file:secret,source:'governed',auth:f.info.auth}];f.client.rename=async()=>({id:'A',title:secret});f.client.archive=async()=>({id:'A',title:secret});f.client.listAgents=async()=>[{name:secret,password:f.info.auth.password}];for(const op of ['list','messages','diff','rename','agents','archive'])outputs.push(await f.boundary.run(op,bodyFor(op)));await f.boundary.run('list',{});f.client.messages=async()=>{throw new Error(secret);};try{await f.boundary.run('messages',{sessionId:'A'});}catch(error){outputs.push({error:error.message,...publicOpenCodeError(error.code)});}const text=JSON.stringify([outputs,f.logs]);assert.equal(forbidden.reduce((n,s)=>n+(text.includes(s)?1:0),0),0);});
test('credential never reaches generated extension or PID state',async t=>{
  resetOpencodeServerSingletonForTests(); const password=randomBytes(32).toString('hex'); let pidContent='';
  const child=new EventEmitter();child.pid=100;child.stdout=new PassThrough();child.kill=()=>child.emit('exit');
  const info=await ensureOpencodeServer({command:'/fixture/opencode',port:45125,env:{OPENCODE_SERVER_PASSWORD:password},processImpl:new EventEmitter(),maxWaitMs:100,
    spawnImpl:()=>{setImmediate(()=>child.stdout.write('listening on http://127.0.0.1:45125\n'));return child;},
    fetchImpl:async(_u,init)=>new Response('{}',{status:init.headers?.Authorization?200:401}),
    pidRecord:{read:async()=>null,write:async(_d,value)=>{pidContent=JSON.stringify(value);},clear(){}}});
  t.after(()=>child.kill());
  const content=[pidContent];
  async function scan(url){for(const item of await readdir(url,{withFileTypes:true})){const path=new URL(item.name+(item.isDirectory()?'/':''),url);if(item.isDirectory())await scan(path);else if(item.isFile() && /\.(?:js|json|html|css)$/.test(item.name))content.push(await readFile(path,'utf8'));}}
  await scan(new URL('../resonantos-side-panel-extension/',import.meta.url));
  const text=content.join('\n');assert.equal([password,info.auth.header,info.auth.header.slice(6)].reduce((n,value)=>n+(text.includes(value)?1:0),0),0);
});
test('cockpit refusal never issues server URL',async t=>{const f=fixture(t);assert.deepEqual(await f.boundary.run('web',{}),{url:'',requiresCredential:true});});
test('concurrent start and list share one owned generation',async t=>{let ensures=0;const f=fixture(t,{ensureServer:async()=>{ensures++;return f.info;}});const results=await Promise.allSettled([f.boundary.run('start',{}),f.boundary.run('list',{})]);assert.deepEqual([ensures,results.every(r=>r.status==='fulfilled')],[1,true]);});
test('revocation awaits attached transport closure',async t=>{const f=fixture(t);await f.boundary.run('start',{});const sub=await f.boundary.openEvents('A');let release;const closed=new Promise(r=>{release=r;});let terminated=false,finished=false;sub.attachTransport({bufferedBytes:()=>0,closed,terminate:async code=>{terminated=code==='OPENCODE_REVOKED';}});const pending=f.boundary.revoke().then(()=>{finished=true;});await turn();const before=[terminated,finished];release();await pending;assert.deepEqual([...before,finished],[true,false,true]);});
test('re-enable requires explicit bootstrap and never revives old subscriptions',async t=>{const f=fixture(t);await f.boundary.run('start',{});const old=await f.boundary.openEvents('A');await f.boundary.revoke();const code=await errorCode(()=>f.boundary.run('messages',{sessionId:'A'}));await f.boundary.run('list',{});const fresh=await f.boundary.openEvents('A');assert.deepEqual([code,old.terminalCode,fresh.terminalCode],['OPENCODE_EXECUTION_DISABLED','OPENCODE_REVOKED',null]);});
test('start at registry capacity does not create an upstream session',async t=>{const f=fixture(t);f.client.listSessions=async()=>Array.from({length:1000},(_,i)=>({id:'s'+i}));await f.boundary.run('list',{});let creates=0;f.client.createSession=async()=>{creates++;return{id:'new'};};const code=await errorCode(()=>f.boundary.run('start',{}));assert.deepEqual([code,creates],['OPENCODE_LIMIT',0]);});
test('over-cap list does not partially adopt sessions',async t=>{const f=fixture(t);await f.boundary.run('start',{});f.client.listSessions=async()=>Array.from({length:1001},(_,i)=>({id:'s'+i}));const code=await errorCode(()=>f.boundary.run('list',{}));await f.boundary.validateEvents('A');assert.deepEqual([code,await errorCode(()=>f.boundary.validateEvents('s0'))],['OPENCODE_LIMIT','OPENCODE_SESSION_UNKNOWN']);});
test('list refresh prunes absent and archived subscriptions',async t=>{const f=fixture(t);await f.boundary.run('start',{});const old=await f.boundary.openEvents('A');f.client.listSessions=async()=>[{id:'A',time:{archived:1}},{id:'B'}];await f.boundary.run('list',{});assert.deepEqual([old.terminalCode,await errorCode(()=>f.boundary.validateEvents('A'))],['OPENCODE_SESSION_UNKNOWN','OPENCODE_SESSION_UNKNOWN']);});
test('runtime credential cannot be adopted as a session identifier',async t=>{const f=fixture(t);f.client.createSession=async()=>({id:f.info.auth.password});assert.equal(await errorCode(()=>f.boundary.run('start',{})),'OPENCODE_PROTOCOL_ERROR');});
test('unexpected TypeError is internal rather than a network diagnosis',async t=>{const f=fixture(t);await f.boundary.run('start',{});f.client.messages=async()=>{throw new TypeError('fixture');};assert.equal(await errorCode(()=>f.boundary.run('messages',{sessionId:'A'})),'OPENCODE_INTERNAL');});
test('fresh bootstrap waits for revoked pending ensure cleanup',async t=>{let resolveOld,entered,ensures=0;const firstEntered=new Promise(r=>{entered=r;});const f=fixture(t,{ensureServer:async()=>{ensures++;if(ensures===1){entered();return new Promise(r=>{resolveOld=r;});}return f.info;}});const old=errorCode(()=>f.boundary.run('start',{}));await firstEntered;await f.boundary.revoke();const fresh=errorCode(()=>f.boundary.run('list',{}));await turn();const countBefore=ensures;resolveOld(f.info);await old;await fresh;assert.equal(countBefore,1);});
test('sanitizer removes nested credential field variants',async()=>{const {sanitizeOpenCodePayload}=await import('../host/opencode-boundary.mjs');const value=randomBytes(32).toString('hex');const output=sanitizeOpenCodePayload({info:{authentication:{value},username:'opencode',client_secret:value,opencode_server_password:value,text:'visible'}},[value]);assert.deepEqual(Object.keys(output.info),['text']);});
